### PR TITLE
Modify readme

### PR DESCRIPTION
**Pull request by sugato1398**
kindly review my PR and suggest any necessary changes/improvements

### CODE REVIEW

**Comment by AnkushSinghGandhi** [comment]
You need to update the demo image of the project @sugato1398

**Comment by sugato1398** [comment]
i understand that i need to replace the first image, so the last image that I put that shows the dad jokes , would it suffice or I need some other snapshot
dad-jokesdemo
?

**Comment by sugato1398** [comment]
updated the PR, let me know of any corrections

**Comment by AnkushSinghGandhi** [comment]
Looks great :+1:

**Comment by AnkushSinghGandhi** [comment]
Merged :smile:

**Pull request merged**
