### PR TITLE
add background and some allignment

### PR DESCRIPTION
**Pull request by Gagansankhla**
I add one background in it hope you liked it and also made some changes in alignment

### CODE REVIEW

**Comment by AnkushSinghGandhi** [comment]
Screenshot from 2021-10-10 18-11-31

**Comment by AnkushSinghGandhi** [comment]
There are some problems with your PR, as I can't see the extension, but I'm labeling you PR as "hacktoberfest-accepted." so it will be counted towards Hacktoberest.

**Comment by AnkushSinghGandhi** [comment]
If you still wanna work you can re-open this PR anytime.

**Comment by Gagansankhla** [comment]
Thank you for your email. I’ll definitely try my best to fix this

**Pull request closed without merging**
